fix TypeError: on_serve() got an unexpected keyword argument 'builder
based on https://github.com/jwaschkau/mkpdfs-mkdocs-plugin/tree/fix/on-server-missing-kwargs